name: Build and Deploy
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
permissions: read-all
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Setup Node
        uses: actions/setup-node@v5
      - name: Build
        run: |
          npm ci -w pipeline
          npm run build -- -- --version=${{ github.ref_name }}
      - name: Upload files as artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dist/
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
